### ISSUE TITLE
ReadPassword don't take stdin

### ISSUE THREAD

**Issue by No-0n3** [tillitis/tkeyutil#4]
Hi,

Found a bug in tkeyutil when using tkey-sign-cli. The bug was when using the switch "--uss" with the client tool. I could enter the USS but not enter the repeated USS. In the link below you see the exact row I could trace the error to.

https://github.com/tillitis/tkeyutil/blob/705090b1e35894c66b4544c12798052ab568ec76/uss.go#L22

The error is in conjunction with that the function term.ReadPassword takes the argument "0" when it should take the same argument as when called in line 17 where it waits for data from stdin.

The bug results in wrongly read USS so USS can't be used correctly.
![Skärmbild 2024-11-04 133850](https://github.com/user-attachments/assets/80a592fc-1fbf-4782-98fe-853bacbdae70)

Have attached a fix to this bug.
[uss.patch](https://github.com/user-attachments/files/17618159/uss.patch)

Br Isaac

**Comment by mchack-work** [comment]
Thank you! This will probably fix issue https://github.com/tillitis/tkey-sign-cli/issues/26
